"""add is_hidden

Revision ID: 10b9400d525d
Revises: 5f67718e65ff
Create Date: 2026-06-04 16:13:57.004817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10b9400d525d'
down_revision: Union[str, Sequence[str], None] = '5f67718e65ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_hidden')
    # ### end Alembic commands ###
