"""add strip

Revision ID: 7400f5f0244b
Revises: 31cb1c096eaf
Create Date: 2026-05-22 16:24:15.121504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7400f5f0244b'
down_revision: Union[str, Sequence[str], None] = '31cb1c096eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('stripe_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'stripe_session_id')
    # ### end Alembic commands ###
