name: FastAPI

on:
  push: 
    branches: ['main']
  pull_request: 
    branches: ['main']

jobs:
  test-in-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Build and start Docker Service
      run: |
        docker compose up -d --build
        sleep 15

    - name: Check Docker Containers Status
      run: docker compose ps

    - name: Run Pytest
      run: docker compose exec -T backend pytese



