name: FastAPI

on:
  push: 
    branches: ['main']
  pull_request: 
    branches: ['main']

jobs:
  test-in-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Create Mock .env File for Testing
      run: |
        echo "POSTGRES_USER=testuser" >> .env
        echo "POSTGRES_PASSWORD=testpassword" >> .env
        echo "POSTGRES_DB=testdb" >> .env
        echo "POSTGRES_URL=postgresql+asyncpg://testuser:testpassword@db:5432/testdb" >> .env
        echo "ALGORITHM=HS256" >> .env 
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
        echo "SECRET_KEY=123456789" >> .env

        echo "REDIS_URL=redis://redis:6379/0" >> .env

        echo "MAIL_USERNAME=test@gmail.com" >> .env
        echo "MAIL_PASSWORD=12346" >> .env
        echo "MAIL_FROM_NAME=test" >> .env

    - name: Build and start Docker Service
      run: |
        docker compose up -d --build
        sleep 15

    

    - name: Check Docker Containers Status
      run: docker compose ps

    - name: Run Pytest
      run: docker compose exec -T backend pytest



